import { GoogleGenAI } from '@google/genai';
import type { VercelRequest, VercelResponse } from '../_types';

const LANGUAGE_CODE: Record<string, string> = {
  en: 'en-US',
  ca: 'ca-ES',
  es: 'es-ES',
};

function parseSampleRate(mimeType: string): number {
  const match = mimeType.match(/rate=(\d+)/i);
  if (!match) return 24000;
  const parsed = parseInt(match[1], 10);
  return Number.isNaN(parsed) ? 24000 : parsed;
}

function pcm16ToWavBuffer(pcmBuffer: Buffer, sampleRate: number): Buffer {
  const channels = 1;
  const bitsPerSample = 16;
  const blockAlign = channels * (bitsPerSample / 8);
  const byteRate = sampleRate * blockAlign;
  const dataSize = pcmBuffer.length;
  const wavBuffer = Buffer.alloc(44 + dataSize);

  wavBuffer.write('RIFF', 0);
  wavBuffer.writeUInt32LE(36 + dataSize, 4);
  wavBuffer.write('WAVE', 8);
  wavBuffer.write('fmt ', 12);
  wavBuffer.writeUInt32LE(16, 16); // PCM chunk size
  wavBuffer.writeUInt16LE(1, 20);  // PCM format
  wavBuffer.writeUInt16LE(channels, 22);
  wavBuffer.writeUInt32LE(sampleRate, 24);
  wavBuffer.writeUInt32LE(byteRate, 28);
  wavBuffer.writeUInt16LE(blockAlign, 32);
  wavBuffer.writeUInt16LE(bitsPerSample, 34);
  wavBuffer.write('data', 36);
  wavBuffer.writeUInt32LE(dataSize, 40);
  pcmBuffer.copy(wavBuffer, 44);

  return wavBuffer;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'POST') {
    return res.status(405).json({ success: false, error: 'Method not allowed' });
  }

  const { text, language, voiceName } = req.body ?? {};
  const inputText = String(text ?? '').trim();

  if (!inputText) {
    return res.status(400).json({ success: false, error: 'Missing required field: text' });
  }

  const apiKey = process.env.GOOGLE_GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ success: false, error: 'GOOGLE_GEMINI_API_KEY not configured' });
  }

  try {
    const ai = new GoogleGenAI({ apiKey });
    const lang = typeof language === 'string' ? language : 'en';

    const langName = lang === 'ca' ? 'Catalan' : lang === 'es' ? 'Spanish' : 'English';

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-preview-tts',
      contents: [
        {
          parts: [
            {
              text: `Say the following in ${langName}, in a warm and friendly tone: ${inputText}`,
            },
          ],
        },
      ],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: {
              voiceName: typeof voiceName === 'string' ? voiceName : 'Kore',
            },
          },
        },
      },
    });

    const candidates = response.candidates ?? [];
    const parts = candidates[0]?.content?.parts ?? [];
    const inlinePart = parts.find((part) => part.inlineData?.data);

    if (!inlinePart?.inlineData?.data) {
      console.error('[speak] No audio in response. Candidates:', JSON.stringify(candidates.map(c => ({
        finishReason: c.finishReason,
        partsCount: c.content?.parts?.length ?? 0,
        partTypes: c.content?.parts?.map(p => Object.keys(p)),
      }))));
      return res.status(500).json({ success: false, error: 'No audio generated by Gemini TTS' });
    }

    const rawAudioBase64 = inlinePart.inlineData.data;
    let mimeType = inlinePart.inlineData.mimeType ?? 'audio/L16;codec=pcm;rate=24000';

    let audioBase64 = rawAudioBase64;
    const lowerMime = mimeType.toLowerCase();

    if (lowerMime.includes('audio/l16') || lowerMime.includes('pcm')) {
      const pcmBuffer = Buffer.from(rawAudioBase64, 'base64');
      const wavBuffer = pcm16ToWavBuffer(pcmBuffer, parseSampleRate(mimeType));
      audioBase64 = wavBuffer.toString('base64');
      mimeType = 'audio/wav';
    }

    return res.status(200).json({
      success: true,
      data: {
        audioBase64,
        mimeType,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    console.error('[speak] TTS error:', message);
    return res.status(500).json({ success: false, error: `Speech generation failed: ${message}` });
  }
}
